sudo: false
language: ruby
rvm:
  - jruby-19mode
  - 1.9.3
  - 2.0.0-p648 # macOS
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-head
before_install: gem install bundler -v '~> 1.15' --conservative
