sudo: false
language: ruby
rvm:
  - 2.0.0-p648 # macOS
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-head
  - rbx-head
before_install: gem install bundler -v '~> 1.15' --conservative
install: bundle install
script: bundle exec rake
